name: NiceCore
author: Rome
version: 1.0
main: fr.rome.nicecore.Main
commands:
  itemgive:
    permission: nicecore.items.give
    description: Give you an items
  clearcooldowns:
    permission: nicecore.items.cooldowns
    description: Skip cooldown for items
    aliases: ["cc"]
  leaderboard:
    description: Check emerald's leaderboard
    aliases: ["lb"]
  add-emerald:
    description: An emerald to your bank